version: '3.3'

volumes:
  pg_data:
  static:
  media:
  static_front:

services:
  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    build: 
      context: ../backend/
      dockerfile: Dockerfile
    env_file: ../.env
    volumes:
      - static_front:/app/static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    build: ../frontend/
    volumes:
      - static:/app/build/
    depends_on:
      - backend

  gateway:
    build:
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/staticfiles/
      - media:/media
      - static_front:/usr/share/nginx/html/
    depends_on:
      - frontend
