version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    build: 
      context: ../backend/
      dockerfile: Dockerfile
    env_file: ../.env
    volumes:
      - static:/backend_static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    build: ../frontend/
    command: cp -r /app/result_build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  gateway:
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/
      - media:/media
    depends_on:
      - frontend
