# Generated by Django 3.2.3 on 2023-07-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на картинку на сайте'),
        ),
    ]
